### ISSUE TITLE
Running twitter-analytics- wrapper on Windows

### ISSUE THREAD

**Issue by strod** [philippe2803/twitter-analytics-wrapper#19]
Hi,

Just tried to run your toy example

```
from twitter_analytics import ReportDownloader


reports = ReportDownloader(
    username='<twitter username>',
    password='<twitter password>',
)

report_filepath = reports.run()
```
(Used the same username and password that I use to loggin in my account)
and got the above error:

```
EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[WinError 2] The system can not find the file specified
Program install error! 
```

I´m running with python 3.7 on Windows

Is it just impossible to use this package on Windows or there is a way to work around that?

**Comment by rogelj** [comment]
You are getting this error because Xvfb was not found. Xvfb is X virtual framebuffer and is not normally included with WIndows. Even in Linux or Mac you need to make sure you have an appropriate installation (see the readme file for the repo). 

You may want to read this post for a potential solution. http://superuser.com/a/480261/124457

I hope that helps.
