### ISSUE TITLE
Class not found: @class="me dropdown session js-session"

### ISSUE THREAD

**Issue by MikVidal** [philippe2803/twitter-analytics-wrapper#3]
```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[@class="me dropdown session js-session"]/a[@href="/settings/account"]"}
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.27,platform=Linux 4.8.0-49-generic x86)

```

**Comment by jgbreezer** [comment]
I have also seen this, and I have a theory (unproven, haven't manually debugged it yet): if you use the downloader too frequently (maybe just a handful of times in a few hours is enough), Twitter will start prompting for your user's email address (with a hint) instead of just logging you in with the password; I presume as a security check.

The downloader is not set up to handle this and obviously can't find the link to access twitter analytics in the page, which is what the error message you see could be about. If this is the case, I suspect a solution is either a) don't run it more than once a day or something (unknown limit); b) extend twitter_analytics to support this page and add an API call parameter to supply the email address; or c) cache the login tokens - recommend have the downloader return them, and they can be passed in to setup the browser  each time or it would use the login credentials if they weren't setup.

**Comment by philippe2803** [comment]
This happens to me sometimes too. If you want to see the browser when running the script (for debugging purposes) you can use show_browser=True as argument in your ReportDownloader object. This will show the browser activity. You can then validate email manually. This should work fine then.

To handle this particular case programmatically, this means adding an extra module to hande email verification. Probably more code than the actual library. If you have some time, make a PR!

**Comment by philippe2803** [comment]
Closing as solution is not in the scope of this library.
